# Generated by Django 5.2.7 on 2025-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
        migrations.AddField(
            model_name='profile',
            name='add',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
