# Generated by Django 5.2.7 on 2025-11-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_latitude_profile_longitude_alter_profile_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add',
        ),
    ]
